### ISSUE TITLE
Gradle Build Failed with app:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by henry000dev** [ckurtm/simple-sql-provider#2]
Hi,

I have setup the library with the latest Gradle configuration, but got the following build error as soon as I added the "TestProviderConfig" class as per the instruction:

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.

> java.lang.NullPointerException

Clean/rebuild didn't help. I also tried different versions of the plugin/libs (e.g. tried javapoet 1.3) but none worked.

Steps to reproduce:
1. Setup Gradle configs as per instruction.
2. Create the new "TestProviderConfig" as per instruction.
3. Build -> get errors here.

I am using Android Studio 1.4 on Windows platform.

My app gradle is:

apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.0"

```
defaultConfig {
    applicationId "projects.nanodegree.henry.popularmovies"
    minSdkVersion 14
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.google.code.gson:gson:2.3.1'

```
compile 'com.squareup:javapoet:1.2.0'
compile 'ckm.simple:simple_sql_provider_annotation:1.0.6'
compile 'ckm.simple:simple_sql_provider_processor:1.0.6'
```

}

Thanks for the library.

**Comment by ckurtm** [comment]
can you give me a setup of the tables your trying to create. not too sure whats going on based on just that. maybe a queue that i need to put in more error logging.

**Comment by henry000dev** [comment]
I figured out the problem... I did a build after adding the TestProviderConfig.java class but BEFORE creating any annotated tables... if I did a build after adding TestProviderConfig AND a annotated table, then the build had no problem.

**Comment by imGurpreetSK** [comment]
Hi, I'm facing the exact same issue for build tools version 2.3.3 and 3.0.0-beta4. Is there any fix for this?
More: It throws the error everytime I build after implementing ProviderConfig and before annotating tables
