### ISSUE TITLE
How to use UpgradeScript?

### ISSUE THREAD

**Issue by bogdan-marian** [ckurtm/simple-sql-provider#3]
Hello. 
I started playing with this very nice tool. I'm not able to figure out how to implement a simple UpgradeScript test. I will also be satisfied if I have the option of dropping all my tables and recreate them using the UpgradeScript class. 

Thank you in advance. 
Bogdan

**Comment by ckurtm** [comment]
Create you're update sql file e.g. from_ver_2 , add it to your "raw" resource folder. say its for updating from version 2 -> version 5
create a UpgradeScript class , give it the oldversion 2 and resource id to your raw sql file i.e. R.raw.from_ver_2.

so your config file would now look like this:

``` java
 @Override
    public UpgradeScript[] getUpdateScripts() {
        return new UpgradeScript[]{
                new UpgradeScript(2,R.raw.from_ver2)
        };
    }
```
