### ISSUE TITLE
Generated class for table does not use "includePrimary" parameter

### ISSUE THREAD

**Issue by MaJerle** [ckurtm/simple-sql-provider#5]
Hello,

thanks for great library.

I'm using it for read and write and it works OK, however, when I use getContentValues from generated class for table, function ignores includePrimary parameter which is important, because on write I don't want to include primary key.

Can you please suggest what to do or you have unsolved bug maybe?

Have a nice day.

**Comment by ckurtm** [comment]
I cant help if you dont show sample code. includePrimary is meant to include the primary field in the generated contentValues. Unless theres something I'm missing from your question.

**Comment by MaJerle** [comment]
Yes, you are right. If I look at function where paraneter should be used, I got warning that it is not used. Lookong at function, there is no checking for this parameter but primary field is always used in .put method.

**Comment by MaJerle** [comment]
I have found a problem, because I forgot to add "primary = true" in @SimpleSQLColumn part. Now it works ok.
