### ISSUE TITLE
Add insertWithConflict option

### ISSUE THREAD

**Issue by aruke** [ckurtm/simple-sql-provider#6]
There is no way of using insertWithConflict with current provider. I can't overwrite rows.

**Comment by ckurtm** [comment]
You can:

using the TodoProvider from the example on Readme:

```
TestProvider provider = TestProvider.getContentProvider(context);
SQLiteDatabase database  = TestProvider.getDatabaseHelper().getWriteableDatabase();
database.insertWithConfict() // whatever you want to do here
```

or you could update, check it there was anything updated else insert.
